### ISSUE TITLE
colorful-logging gives an error during building

### ISSUE THREAD

**Issue by Oreolek** [furkleindustries/inklecate-wasm#5]
Node 14.4.0, webpack 4.43.0

```
Module build failed (from ./node_modules/.pnpm/inklecate-loader@1.5.4/node_modules/inklecate-loader/index.js):
[path]/node_modules/.pnpm/colorful-logging@1.3.3/node_modules/colorful-logging/index.js:1
(function (exports, require, module, __filename, __dirname) { export {
                                                              ^^^^^^

SyntaxError: Unexpected token 'export'
    at new Script (vm.js:99:7)
    at NativeCompileCache._moduleCompile ([path]/node_modules/.pnpm/v8-compile-cache@2.0.3/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
    at Module._compile ([path]/node_modules/.pnpm/v8-compile-cache@2.0.3/node_modules/v8-compile-cache/v8-compile-cache.js:186:36)
[...]
```

Is this module necessary?

**Comment by furkle** [comment]
hi oreolek! your guess here is absolutely correct. `colorful-logging` was a silly idea of mine in the first place, and it's exactly the sort of thing which doesn't belong in a utility library.

i will have actual time to pay attention to this soon, but my recollection, complexified as it has been by this most stressful of years, is that the reason i hadn't fixed that is because the wasm codebase more or less needs a full overhaul. ooui-wasm changed in such a way that i can't get it to output what it did before, loading all of mono.js and all the CLR dlls before even being able to reference the useful parts of the module is a terrible user experience, and even the "working" proofs of concept in past versions neglected to include any possibility for counting all visits rather than the base visit types, which is hardly forward-compatible.

i'm honestly not sure what's best for this lib at this point. could be deprecation, could be rewrite, could be just sticking it in the back and letting it rot until MS or mono offers a reasonable way to load a single CLI library in a browser. happy to listen to whatever ideas you have, or let you at them as you see fit. just let me know your thoughts.

**Comment by Oreolek** [comment]
Well I actually wrote an issue in the wrong repo 😅 i just wanted to use `inklecate-loader` to compile ink in node.js during the building, not in the browser. The `colorful-logging` package is linked in both.

**Comment by furkle** [comment]
oh, that i can fix! give me a a day, i'll let you know
